// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace UnrealWizard
{
    internal sealed partial class Vsix
    {
        public const string Id = "UnrealWizard.9096c466-c543-48d9-bd48-7766aedbe318";
        public const string Name = "UnrealWizard";
        public const string Description = @"Adds context menu options to filters inside of Unreal Engine C++ projects for easily adding directories and classes";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Dakota Cardillo";
        public const string Tags = "";
    }
}
