// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace UnrealWizard
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string UnrealWizardString = "252cf685-cded-4bd7-8d49-5fd125157a3b";
        public static Guid UnrealWizard = new Guid(UnrealWizardString);

        public const string AbstractCubeString = "34d43eca-c84f-4ee2-9398-a842a94a1ea6";
        public static Guid AbstractCube = new Guid(AbstractCubeString);

        public const string AddFolderString = "f678f4af-e06b-4e42-9747-88f23a22e77a";
        public static Guid AddFolder = new Guid(AddFolderString);

        public const string AddMethodString = "11df06ed-b9b2-4c50-90fd-5a1040d46f53";
        public static Guid AddMethod = new Guid(AddMethodString);

        public const string AddToSolutionExplorerString = "f4635519-3b76-48d8-aa3b-4f83dcb189b2";
        public static Guid AddToSolutionExplorer = new Guid(AddToSolutionExplorerString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int UnrealWizardGroup = 0x0001;
        public const int UEClassWindow = 0x0100;
        public const int CreateSyncedFilter = 0x0010;
        public const int AbstractCubeIcon = 0x0001;
        public const int AddFolderIcon = 0x0001;
        public const int AddMethodIcon = 0x0001;
        public const int AddToSolutionExplorerIcon = 0x0001;
    }
}